# ### Simple

require "../src/cronic"
include Cronic

p! Cronic.parse("thursday")
p! Cronic.parse("november")
p! Cronic.parse("summer")
p! Cronic.parse("friday 13:00")
p! Cronic.parse("mon 2:35")
p! Cronic.parse("4pm")
p! Cronic.parse("10 to 8")
p! Cronic.parse("10 past 2")
p! Cronic.parse("half past 2")
p! Cronic.parse("6 in the morning")
p! Cronic.parse("friday 1pm")
p! Cronic.parse("sat 7 in the evening")
p! Cronic.parse("yesterday")
p! Cronic.parse("today")
p! Cronic.parse("tomorrow")
p! Cronic.parse("last week")
p! Cronic.parse("next week")
p! Cronic.parse("this tuesday")
p! Cronic.parse("next month")
p! Cronic.parse("last winter")
p! Cronic.parse("this morning")
p! Cronic.parse("last night")
p! Cronic.parse("this second")
p! Cronic.parse("yesterday at 4:00")
p! Cronic.parse("last friday at 20:00")
p! Cronic.parse("last week tuesday")
p! Cronic.parse("tomorrow at 6:45pm")
p! Cronic.parse("afternoon yesterday")
p! Cronic.parse("thursday last week")

# ### Complex

p! Cronic.parse("3 years ago")
p! Cronic.parse("a year ago")
p! Cronic.parse("5 months before now")
p! Cronic.parse("7 hours ago")
p! Cronic.parse("7 days from now")
p! Cronic.parse("1 week hence")
p! Cronic.parse("in 3 hours")
p! Cronic.parse("1 year ago tomorrow")
p! Cronic.parse("3 months ago saturday at 5:00 pm")
p! Cronic.parse("7 hours before tomorrow at noon")
p! Cronic.parse("3rd wednesday in november")
p! Cronic.parse("3rd month next year")
p! Cronic.parse("3rd thursday this september")
p! Cronic.parse("4th day last week")
p! Cronic.parse("fourteenth of june 2010 at eleven o'clock in the evening")
p! Cronic.parse("may seventh '97 at three in the morning")

# ### Specific Dates

p! Cronic.parse("January 5")
p! Cronic.parse("22nd of june")
p! Cronic.parse("5th may 2017")
p! Cronic.parse("February twenty first")
p! Cronic.parse("dec 25")
p! Cronic.parse("may 27th")
p! Cronic.parse("October 2006")
p! Cronic.parse("oct 06")
p! Cronic.parse("jan 3 2010")
p! Cronic.parse("february 14, 2004")
p! Cronic.parse("february 14th, 2004")
p! Cronic.parse("3 jan 2000")
p! Cronic.parse("17 april 85")
p! Cronic.parse("5/27/1979")
p! Cronic.parse("27/5/1979")
p! Cronic.parse("05/06")
p! Cronic.parse("1979-05-27")
p! Cronic.parse("Friday")
p! Cronic.parse("5")
p! Cronic.parse("4:00")
p! Cronic.parse("17:00")
p! Cronic.parse("0800")

# ### Specific Times (many of the above with an added time)

p! Cronic.parse("January 5 at 7pm")
p! Cronic.parse("22nd of june at 8am")
p! Cronic.parse("1979-05-27 05:00:00")
p! Cronic.parse("03/01/2012 07:25:09.234567")
p! Cronic.parse("2013-08-01T19:30:00.345-07:00")
p! Cronic.parse("2013-08-01T19:30:00.34-07:00")
